- CHANGELOG.md
- README.md
- package.json
- projects/nextjs/lib/$path.ts
- projects/nuxtjs/plugins/$path.ts
- src/createNextTemplate.ts
- src/createNuxtTemplate.ts
- src/getConfig.ts
> chore(release): 0.8.0

- CHANGELOG.md
- README.md
- package.json
- projects/nextjs/lib/$path.ts
- projects/nuxtjs/plugins/$path.ts
- src/createNextTemplate.ts
- src/createNuxtTemplate.ts
> chore(release): 0.9.0

- CHANGELOG.md
- package.json
- projects/nextjs/lib/$path.ts
- projects/nuxtjs/plugins/$path.ts
- src/createNextTemplate.ts
- src/createNuxtTemplate.ts
> chore(release): 0.9.1

- CHANGELOG.md
- README.md
- __tests__/index.spec.ts
- package.json
- projects/nuxtjs-no-slash/nuxt.config.ts
- projects/nuxtjs-no-slash/pages/_pid.tsx
- projects/nuxtjs-no-slash/pages/blog/_slug.tsx
- projects/nuxtjs-no-slash/pages/index.tsx
- projects/nuxtjs-no-slash/plugins/$path.ts
- src/buildTemplate.ts
- src/createNuxtTemplate.ts
> chore(release): 0.9.2

- CHANGELOG.md
- package.json
- projects/nextjs/lib/$path.ts
- src/createNextTemplate.ts
> chore(release): 0.9.3

- CHANGELOG.md
- package.json
- projects/nextjs/lib/$path.ts
- projects/nuxtjs-no-slash/plugins/$path.ts
- projects/nuxtjs/plugins/$path.ts
- src/createNextTemplate.ts
> chore(release): 0.9.4

- CHANGELOG.md
- README.md
- __tests__/index.spec.ts
- package.json
- projects/nextjs-src/src/pages/[pid].tsx
- projects/nextjs-src/src/pages/_app.tsx
- projects/nextjs-src/src/pages/blog/[...slug].tsx
- projects/nextjs-src/src/pages/index.tsx
- projects/nextjs-src/src/utils/$path.ts
- projects/nuxtjs-src/client/pages/_pid.tsx
- projects/nuxtjs-src/client/pages/blog/_slug.tsx
- projects/nuxtjs-src/client/pages/index.tsx
- projects/nuxtjs-src/client/plugins/$path.ts
- projects/nuxtjs-src/nuxt.config.ts
- projects/nuxtjs/nuxt.config.js
- src/createNextTemplate.ts
- src/getConfig.ts
> chore(release): 0.10.0

- CHANGELOG.md
- README.md
- package.json
- projects/nextjs-src/src/utils/$path.ts
- projects/nextjs/lib/$path.ts
- src/createNextTemplate.ts
> chore(release): 0.10.1

- CHANGELOG.md
- README.md
- package.json
- projects/nuxtjs-no-slash/plugins/$path.ts
- projects/nuxtjs-src/client/plugins/$path.ts
- projects/nuxtjs/plugins/$path.ts
- src/createNuxtTemplate.ts
> chore(release): 0.10.2

- CHANGELOG.md
- README.md
- __tests__/index.spec.ts
- package.json
- src/cli.ts
- src/getConfig.ts
- yarn.lock
> chore(release): 0.11.0

- __tests__/index.spec.ts
- package.json
- projects/nextjs-basepath/lib/$path.ts
- projects/nextjs-basepath/next.config.js
- projects/nextjs-basepath/pages/[pid].tsx
- projects/nextjs-basepath/pages/_app.tsx
- projects/nextjs-basepath/pages/blog/[...slug].tsx
- projects/nextjs-basepath/pages/index.tsx
- projects/nuxtjs-basepath/nuxt.config.js
- projects/nuxtjs-basepath/pages/_pid.tsx
- projects/nuxtjs-basepath/pages/blog/_slug.tsx
- projects/nuxtjs-basepath/pages/index.tsx
- projects/nuxtjs-basepath/plugins/$path.ts
- src/buildTemplate.ts
- src/createStaticTemplate.ts
- src/getConfig.ts
- yarn.lock
closes https://github.com/aspida/pathpida/issues/24
> feat!: support basepath config for staticPath

- README.md
- Fixed typo in onClick attribute.
- Changed the `onclick` variable names to `onClick`  along with the above change. (If this changes aren't needed, I'll cancel it !! )
> Fix some typo in onClick attribute in README.md

- CHANGELOG.md
- package.json
- projects/nextjs-basepath/utils/$path.ts
- projects/nextjs-src/src/utils/$path.ts
- projects/nextjs/lib/$path.ts
- projects/nuxtjs-basepath/plugins/$path.ts
- projects/nuxtjs-src/client/plugins/$path.ts
- projects/nuxtjs/plugins/$path.ts
- src/createNextTemplate.ts
- src/createNuxtTemplate.ts
- src/createStaticTemplate.ts
- src/replaceWithUnderscore.ts
- yarn.lock
> chore(release): 0.13.1

- CHANGELOG.md
- package.json
- projects/nuxtjs-basepath/plugins/$path.ts
- projects/nuxtjs-no-slash/plugins/$path.ts
- projects/nuxtjs-src/client/plugins/$path.ts
- projects/nuxtjs/plugins/$path.ts
- src/buildTemplate.ts
- yarn.lock
> chore(release): 0.15.1

- projects/nextjs/lib/$path.ts
- src/createNextTemplate.ts
next.jsのプロジェクトでpathpidaを利用しています。下記のようなディレクトリ構成で[authorId].tsx用のルーティングが書き出されませんでした。
- /[authorId].tsx
- /[authorId]/[bookId].tsx
同じ名前のディレクトリとファイルが存在しても、どちらのルーティングも書き出されるようにしました。
> Support duplicate file and directory names

- CHANGELOG.md
- package.json
- projects/nextjs/lib/$path.ts
- src/createNextTemplate.ts
- yarn.lock
> chore(release): 0.15.2

- .github/workflows/nodejs.yml
- CHANGELOG.md
- package.json
- yarn.lock
> chore(release): 0.15.3

- CHANGELOG.md
- package.json
- src/createNextTemplate.ts
- src/createNuxtTemplate.ts
- src/createSapperTemplate.ts
- src/getConfig.ts
- yarn.lock
> chore(release): 0.15.5

- __tests__/index.spec.ts
- resolves #106
- resolves #
- 試しにsetTimeout追加してみました
Please upvode with reacting as :+1: to express your agreement.
> fix: add setTimeout

- CHANGELOG.md
- README.md
- resolves #
- resolves #
https://github.com/aspida/pathpida/issues/114
- ...
Please upvode with reacting as :+1: to express your agreement.
> docs: update changelog and place warning in readme

- projects/nextjs-basepath/out/lib/basic/$path.ts
- projects/nextjs-basepath/out/lib/ignore/$path.ts
- projects/nextjs-basepath/out/lib/static/$path.ts
- projects/nextjs-basepath/utils/$path.ts
- projects/nextjs-custom-ext/lib/$path.ts
- projects/nextjs-custom-ext/out/lib/basic/$path.ts
- projects/nextjs-custom-ext/out/lib/ignore/$path.ts
- projects/nextjs-custom-ext/out/lib/static/$path.ts
- projects/nextjs-src/src/out/lib/basic/$path.ts
- projects/nextjs-src/src/out/lib/ignore/$path.ts
- projects/nextjs-src/src/out/lib/static/$path.ts
- projects/nextjs-src/src/utils/$path.ts
- projects/nextjs/lib/$path.ts
- projects/nextjs/out/lib/basic/$path.ts
- projects/nextjs/out/lib/ignore/$path.ts
- projects/nextjs/out/lib/static/$path.ts
- projects/nextjs/pages/%E6%97%A5%E6%9C%AC%E8%AA%9E/index.tsx
- src/createNextTemplate.ts
- fix: stringify to enclose path name into quotations
- regenerate
- resolves https://github.com/aspida/pathpida/issues/125
- resolves #
- ...
Please upvote with reacting as :+1: to express your agreement.
> fix: stringify to enclose path name into quotations

- CHANGELOG.md
- src/getConfig.ts
- resolves #
- resolves #
- ...
Please upvote with reacting as :+1: to express your agreement.
> fix: input path of appDir

- CHANGELOG.md
- src/getConfig.ts
- resolves #
- resolves #
- ...
Please upvote with reacting as :+1: to express your agreement.
> fix: change srcDir logic

- CHANGELOG.md
- __tests__/index.spec.ts
- src/buildTemplate.ts
- src/cli.ts
- src/getConfig.ts
- src/nextjs/createNextTemplate.ts
- resolves #
- resolves #
- ...
Please upvote with reacting as :+1: to express your agreement.
> fix: support for cases without pages dir
